/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/items': {
    get: operations['listItems'];
    post: operations['createItem'];
  };
  [key: `/items/${number}`]: {
    delete: operations['deleteItem'];
  };
}

export interface components {
  schemas: {
    Item: {
      name: string;
      title?: string;
      description?: string;
    };
    ItemWithId: components['schemas']['Item'] & {
      id: number;
    };
    ItemFilter: {
      id?: number;
      name?: string;
      title?: string;
      description?: string;
    };
    PaginationRequest: {
      page?: number;
      per?: number;
    };
    PaginationResponse: {
      page: number;
      per: number;
      total: number;
    };
  };
}

export interface operations {
  listItems: {
    parameters: {
      query: {
        /** Filter item */
        id?: components['schemas']['ItemFilter'];
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': {
            items: components['schemas']['ItemWithId'][];
          } & {
            pagination: unknown;
          };
        };
      };
    };
  };
  createItem: {
    responses: {
      /** Item was created */
      201: {
        content: {
          'application/json': unknown;
        };
      };
    };
    /** New item data */
    requestBody: {
      content: {
        'application/json': components['schemas']['Item'];
      };
    };
  };
  deleteItem: {
    parameters: {
      path: {
        /** ID of item to delete */
        item_id: number;
      };
    };
    responses: {
      /** Item was deleted */
      204: never;
    };
  };
}

export interface external {}

export enum ApiPaths {
  listItems = '/items',
  createItem = '/items',
  deleteItem = '/items/:item_id',
}
